import { SkillEnum } from '../../types/enums';

// Change the track ID every time the [ Track Collection ] changes
export const BOOKINGS_PACK = [
  {
    trackID: '62213f5f6fb4152f6114e349',
    userID: 'invented_id',
    bName: 'Test',
    bEmail: 'test@test.com',
    bDate: 'This will be passed as a parameter',
    initTime: '08:30',
    endTime: '09:30',
    duration: 60,
    openGame: true,
    host: 'invented_id',
    players: ['invented_id'],
    stillJoinable: true,
    minSkill: SkillEnum.noob,
    maxSkill: SkillEnum.amateur,
  },
  {
    trackID: '62213f5f6fb4152f6114e349',
    userID: 'invented_id',
    bName: 'Test 2',
    bEmail: 'test@test.com',
    bDate: 'This will be passed as a parameter',
    initTime: '09:30',
    endTime: '10:30',
    duration: 60,
    openGame: true,
    host: 'invented_id',
    players: ['invented_id'],
    stillJoinable: true,
    minSkill: SkillEnum.pro,
    maxSkill: SkillEnum.pro,
  },
  {
    trackID: '62213f5f6fb4152f6114e349',
    userID: 'invented_id',
    bName: 'Test 3',
    bEmail: 'test@test.com',
    bDate: 'This will be passed as a parameter',
    initTime: '16:30',
    endTime: '18:00',
    duration: 90,
    openGame: true,
    host: 'invented_id',
    players: ['invented_id'],
    stillJoinable: true,
    minSkill: SkillEnum.any,
    maxSkill: SkillEnum.any,
  },
  {
    trackID: '62213f5f6fb4152f6114e349',
    userID: 'invented_id',
    bName: 'Test 4',
    bEmail: 'test@test.com',
    bDate: 'This will be passed as a parameter',
    initTime: '18:30',
    endTime: '19:30',
    duration: 60,
    openGame: false,
  },
  {
    trackID: '62213f5f6fb4152f6114e349',
    bName: 'Test 5',
    bEmail: 'test@test.com',
    bDate: 'This will be passed as a parameter',
    initTime: '19:30',
    endTime: '20:30',
    duration: 60,
    openGame: false,
  },
  {
    trackID: '62213f5f6fb4152f6114e349',
    bName: 'Test 6',
    bEmail: 'test@test.com',
    bDate: 'This will be passed as a parameter',
    initTime: '20:30',
    endTime: '22:30',
    duration: 120,
    openGame: false,
  },
];

export const DEFAULT_TRACKS = [
  'duo', 'duo', 'duo', 'duo', 'duo', 'duo',
  'solo',
  'padbol', 'padbol'
];
